### ISSUE TITLE
Indent includes

### ISSUE THREAD

**Issue by gigafied** [timrwood/includer#7]
Would be nice to be able to prepend each line of an include with an indent. Something like:

``` js
include('./some-file', {indent : '\t'});
```

**Comment by timrwood** [comment]
Yeah, definitely.

I need to read up on source maps to see how changing indentation would affect things, but this would be a good addition. Especially as the example in the readme has indentation.

I think adding something in the [File#wrap](https://github.com/timrwood/includer/blob/6a67093382ba9c4a6b1b30547760f273ead8480f/lib/File.js#L28-L33) method would probably work. Split on newlines and join on newlines + tabs.

Actually, now that I think about it, you could probably do something like this right now.

``` js
include('./some-file', {
    wrap : function (src) {
        return '(function(){\n' + src.replace(/\n/g, '\n\t') + '\n})();';
    }
});
```

**Comment by gigafied** [comment]
Oh nice, I didn't realize you could specify options with each include.
