### ISSUE TITLE
Infinite loop caused by recursive imports

### ISSUE THREAD

**Issue by isochronous** [timrwood/includer#8]
Although the documentation lists `include('./*.js')` as a valid include pattern, when I attempt to use it, includer seems to enter an infinite loop and simply hangs until I Ctrl-C out of it.

Also, the NPM package seems to be out of date.  Even when I did a `npm install includer@0.0.2` I didn't get the code that's currently in the master branch, and there's not a version 0.0.3 either.  I had to manually save the files from github to get the latest version.

**Comment by isochronous** [comment]
In case it's useful, I'm using includer via the `gulp-includer` plugin, I'm on a Windows machine, and like I said, I updated the "includer" node module manually to get the latest version.

**Comment by timrwood** [comment]
Yeah, there are a few commits that were not released on npm yet, not sure why I forgot to do that.

I added a test for recursively including the current file and it seems to work, so I'm guessing those commits fixed it. Are things working as expected when you hotfixed the code from the master branch? If so, I'll just release `0.0.3`.

**Comment by isochronous** [comment]
Well, it's still not working for me - I've put a log file up on pastebin (I added the node-debug module and put in a bunch of debug statements), but first a little context.  This is the folder/file structure in my test project:
![image](https://cloud.githubusercontent.com/assets/774609/2855816/659ff1fa-d161-11e3-9a7f-4ba287080550.png)
Every `.combined.js` file does a `include('./*.js')`, and then the `audit/audit.combined.js` file also has `include('reports/auditReport.js')`, and `resolution/resolution.combined.js` also has `include('../audit/audit.combined.js')`.  The files are saved to a "build" directory after processing, so the originals aren't overwritten.

I've uploaded a zipfile with the basic project structure/files, the gulpfile I'm using (I've been running it via `node gulpfile.js` while debugging), and the gulp-includer plugin that has the version of includer that I've added the debug statements to.  You can give it a test on your machine, and check out the debug log I posted, and maybe see what I'm talking about.

In the meantime, I've gotten around the problem by changing `include('./*.js')` in `audit.combined.js` to `include('./!(audit.combined).js');`, and updated to similar patterns in the other `.combined.js` files.

Here's the debug log: http://pastebin.com/YjknzdcU
And here's the zip file: https://dl.dropboxusercontent.com/u/68572/includer%20infinite%20loop%20example%20project.zip

**Comment by timrwood** [comment]
Hmm, looks like glob is changing `\` in paths to `/`. See these lines in the output logs.

```
includer GlobNode finding files in node: D:\dev\test\rigger\src\audit\audit.js
includer checking to see if file has already been seen: D:/dev/test/rigger/src/audit/audit.js
```

Maybe try a change like this on line 33 of `GlobNode.js`.

``` js
var path = require('path');
node.nodes = files
  .filter(function (filepath) {
    return path.resolve(filepath);
  })
  .filter(node.file.seen.bind(node.file))
  .map(filepathToFileNode.bind(null, node));
```

Sorry for the remote debugging, I don't have a windows machine to test on.

**Comment by isochronous** [comment]
You, sir, are awesome... but the solution isn't complete.  A similar line needs to be added to the `seen` method in the `File` module:

``` js
// at the top of the file
var path = require('path');

// and then
File.prototype.seen = function (filepath) {
    filepath = path.resolve(filepath);
    if (this._seen[filepath]) {
        this.debug('"' + filepath + '" skipped because it was already included.');
        return false;
    }
    return true;
};
```

**Comment by isochronous** [comment]
If you like, I can just submit a pull request to save you some effort, though if you would publish the new version to npm and update the version dependency in the gulp-includer plugin, that would be a HUGE help to my team =)
